#ifndef __OPCODE_H_
#define __OPCODE_H_

#define CALL_ADDR		"0NNN"
#define DISP_CLR		"00E0"
#define RTRN			"00EE"
#define JUMP_ADDR		"1NNN"
#define CALL_SUB		"2NNN"
#define IFEQ_VXNN		"3XNN"
#define IFNE_VXNN		"4XNN"
#define IFEQ_VXVY		"5XY0"
#define SET_VXNN		"6XNN"
#define SET_VXVY		"8XY0"
#define SET_ORVXY		"8XY1"
#define SET_ANDVXY		"8XY2"
#define SET_XORVXVY		"8XY3"
#define ADD_NNVX		"7XNN"
#define ADD_VYVX		"8XY4"
#define ADD_VXL			"FX1E"
#define SUB_VYVX		"8XY5"
#define SHIFTR_VXVF		"8XY6"
#define SHIFTL_VXVF		"8XYE"
#define VXVY_SUBVX		"8XY7"
#define IFNVXVY			"9XY0"
#define SET_LNNN		"ANNN"
#define J_NNNV0			"BNNN"
#define SET_VXRANDNN	"CXNN"
#define DRAW_SPRITE		"DXYN"
#define KEY_UP			"EXA1"
#define KEY_DOWN		"EX9E"
#define HALT_UNTKEY		"FX0A"
#define SET_VXDELAYTIM	"FX07"
#define SET_DELAYTIM	"FX15"
#define SET_SOUNDTIM	"FX18"
#define SET_L_SPRITEVX	"FX29"
#define STORE_BCDVX		"FX33"
#define STORE_V0VX		"FX55"
#define FILL_V0VX		"FX65"

#endif // __OPCODE_H_